module.exports = Object.freeze ({
    LISTING_TYPES : ["AdoptedList", "AdoptionList", "LostFoundList"],

    TYPES : ["dog", "cat", "rabbit", "small_furry", "horse", "bird", "scales_fins_other", "barnyard"],
    GENDERS : ["male", "female", "unknown"],
    SIZE : ["small", "medium", "large", "xlarge"],
    AGE : ["baby", "young", "adult", "senior"],
    COAT : ["short", "medium", "long", "wire", "hairless", "curly"],
    STATUS : ["adoptable", "adopted", "found"],

    DOG :  {
    "name":"Dog",
    "coats":[
        "Hairless",
        "Short",
        "Medium",
        "Long",
        "Wire",
        "Curly"
    ],
    "colors":[
        "Apricot / Beige",
        "Bicolor",
        "Black",
        "Brindle",
        "Brown / Chocolate",
        "Golden",
        "Gray / Blue / Silver",
        "Harlequin",
        "Merle (Blue)",
        "Merle (Red)",
        "Red / Chestnut / Orange",
        "Sable",
        "Tricolor (Brown, Black, & White)",
        "White / Cream",
        "Yellow / Tan / Blond / Fawn"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"Affenpinscher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Afghan Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Airedale Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Akbash","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Akita","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Alaskan Malamute","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Bulldog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Bully","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Eskimo Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Foxhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Hairless Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Staffordshire Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"American Water Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Anatolian Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Appenzell Mountain Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Aussiedoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Australian Cattle Dog / Blue Heeler","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Australian Kelpie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Australian Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Australian Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Basenji","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Basset Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Beagle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bearded Collie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Beauceron","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bedlington Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Belgian Shepherd / Laekenois","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Belgian Shepherd / Malinois","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Belgian Shepherd / Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Belgian Shepherd / Tervuren","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bernedoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bernese Mountain Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bichon Frise","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Black and Tan Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Black Labrador Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Black Mouth Cur","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Black Russian Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bloodhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Blue Lacy","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bluetick Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Boerboel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bolognese","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Border Collie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Border Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Borzoi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Boston Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bouvier des Flandres","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Boxer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Boykin Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Briard","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Brittany Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Brussels Griffon","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bull Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Bullmastiff","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cairn Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Canaan Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cane Corso","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cardigan Welsh Corgi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Carolina Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Catahoula Leopard Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cattle Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Caucasian Sheepdog / Caucasian Ovtcharka","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cavachon","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cavalier King Charles Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cavapoo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chesapeake Bay Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chihuahua","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chinese Crested Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chinese Foo Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chinook","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chiweenie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chocolate Labrador Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Chow Chow","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cirneco dell'Etna","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Clumber Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cockapoo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Cocker Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Collie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Corgi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Coton de Tulear","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Curly-Coated Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dachshund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dalmatian","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dandie Dinmont Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Doberman Pinscher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dogo Argentino","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dogue de Bordeaux","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Dutch Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Bulldog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Cocker Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Foxhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Pointer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Setter","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Springer Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"English Toy Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Entlebucher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Eskimo Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Feist","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Field Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Fila Brasileiro","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Finnish Lapphund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Finnish Spitz","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Flat-Coated Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Fox Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Foxhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"French Bulldog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Galgo Spanish Greyhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"German Pinscher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"German Shepherd Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"German Shorthaired Pointer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"German Spitz","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"German Wirehaired Pointer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Giant Schnauzer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Glen of Imaal Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Golden Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Goldendoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Gordon Setter","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Great Dane","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Great Pyrenees","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Greater Swiss Mountain Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Greyhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Hamiltonstovare","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Harrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Havanese","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Hovawart","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Husky","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Ibizan Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Icelandic Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Illyrian Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Irish Setter","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Irish Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Irish Water Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Irish Wolfhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Italian Greyhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Jack Russell Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Japanese Chin","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Jindo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Kai Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Karelian Bear Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Keeshond","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Kerry Blue Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Kishu","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Klee Kai","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Komondor","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Kuvasz","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Kyi Leo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Labradoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Labrador Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Lakeland Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Lancashire Heeler","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Leonberger","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Lhasa Apso","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Lowchen","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Lurcher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Maltese","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Maltipoo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Manchester Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Maremma Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Mastiff","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"McNab","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Miniature Bull Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Miniature Dachshund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Miniature Pinscher","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Miniature Poodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Miniature Schnauzer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Mixed Breed","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Morkie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Mountain Cur","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Mountain Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Munsterlander","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Neapolitan Mastiff","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"New Guinea Singing Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Newfoundland Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Norfolk Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Norwegian Buhund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Norwegian Elkhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Norwegian Lundehund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Norwich Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Nova Scotia Duck Tolling Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Old English Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Otterhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Papillon","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Parson Russell Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Patterdale Terrier / Fell Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pekingese","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pembroke Welsh Corgi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Peruvian Inca Orchid","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Petit Basset Griffon Vendeen","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pharaoh Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pit Bull Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Plott Hound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pointer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Polish Lowland Sheepdog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pomeranian","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pomsky","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Poodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Portuguese Podengo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Portuguese Water Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Presa Canario","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pug","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Puggle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Puli","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pumi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Pyrenean Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Rat Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Redbone Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Rhodesian Ridgeback","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Rottweiler","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Rough Collie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Saint Bernard","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Saluki","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Samoyed","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sarplaninac","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Schipperke","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Schnauzer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Schnoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Scottish Deerhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Scottish Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sealyham Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Setter","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shar-Pei","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sheep Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sheepadoodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shetland Sheepdog / Sheltie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shiba Inu","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shih poo","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shih Tzu","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Shollie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Siberian Husky","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Silky Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Skye Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sloughi","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Smooth Collie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Smooth Fox Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"South Russian Ovtcharka","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Spanish Water Dog","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Spinone Italiano","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Spitz","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Staffordshire Bull Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Standard Poodle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Standard Schnauzer","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Sussex Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Swedish Vallhund","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Tennessee Treeing Brindle","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Thai Ridgeback","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Tibetan Mastiff","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Tibetan Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Tibetan Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Tosa Inu","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Toy Fox Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Toy Manchester Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Treeing Walker Coonhound","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Vizsla","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Weimaraner","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Welsh Springer Spaniel","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Welsh Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"West Highland White Terrier / Westie","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Wheaten Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Whippet","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"White German Shepherd","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Wire Fox Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Wirehaired Dachshund","_links":{"type":{"href":"/v2/types/dog"}}},{"name":"Wirehaired Pointing Griffon","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Wirehaired Terrier","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Xoloitzcuintli / Mexican Hairless","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Yellow Labrador Retriever","_links":{"type":{"href":"/v2/types/dog"}}},
        {"name":"Yorkshire Terrier","_links":{"type":{"href":"/v2/types/dog"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/dog"
        },
        "breeds":{
            "href":"/v2/types/dog/breeds"
        }
    }
    },
    CAT : {
    "name":"Cat",
    "coats":[
        "Hairless",
        "Short",
        "Medium",
        "Long"
    ],
    "colors":[
        "Black",
        "Black & White / Tuxedo",
        "Blue Cream",
        "Blue Point",
        "Brown / Chocolate",
        "Buff & White",
        "Buff / Tan / Fawn",
        "Calico",
        "Chocolate Point",
        "Cream / Ivory",
        "Cream Point",
        "Dilute Calico",
        "Dilute Tortoiseshell",
        "Flame Point",
        "Gray & White",
        "Gray / Blue / Silver",
        "Lilac Point",
        "Orange & White",
        "Orange / Red",
        "Seal Point",
        "Smoke",
        "Tabby (Brown / Chocolate)",
        "Tabby (Buff / Tan / Fawn)",
        "Tabby (Gray / Blue / Silver)",
        "Tabby (Leopard / Spotted)",
        "Tabby (Orange / Red)",
        "Tabby (Tiger Striped)",
        "Torbie",
        "Tortoiseshell",
        "White"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"Abyssinian","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"American Bobtail","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"American Curl","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"American Shorthair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"American Wirehair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Applehead Siamese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Balinese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Bengal","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Birman","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Bombay","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"British Shorthair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Burmese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Burmilla","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Calico","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Canadian Hairless","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Chartreux","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Chausie","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Chinchilla","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Cornish Rex","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Cymric","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Devon Rex","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Dilute Calico","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Dilute Tortoiseshell","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Domestic Long Hair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Domestic Medium Hair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Domestic Short Hair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Egyptian Mau","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Exotic Shorthair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Extra-Toes Cat / Hemingway Polydactyl","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Havana","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Himalayan","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Japanese Bobtail","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Javanese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Korat","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"LaPerm","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Maine Coon","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Manx","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Munchkin","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Nebelung","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Norwegian Forest Cat","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Ocicat","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Oriental Long Hair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Oriental Short Hair","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Oriental Tabby","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Persian","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Pixiebob","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Ragamuffin","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Ragdoll","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Russian Blue","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Scottish Fold","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Selkirk Rex","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Siamese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Siberian","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Silver","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Singapura","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Snowshoe","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Somali","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Sphynx / Hairless Cat","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Tabby","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Tiger","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Tonkinese","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Torbie","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Tortoiseshell","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Toyger","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Turkish Angora","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Turkish Van","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"Tuxedo","_links":{"type":{"href":"/v2/types/cat"}}},
        {"name":"York Chocolate","_links":{"type":{"href":"/v2/types/cat"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/cat"
        },
        "breeds":{
            "href":"/v2/types/cat/breeds"
        }
    }
    },
    RABBIT : {
    "name":"Rabbit",
    "coats":[
        "Short",
        "Long"
    ],
    "colors":[
        "Agouti",
        "Black",
        "Blue / Gray",
        "Brown / Chocolate",
        "Cream",
        "Lilac",
        "Orange / Red",
        "Sable",
        "Silver Marten",
        "Tan",
        "Tortoiseshell",
        "White"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"American","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"American Fuzzy Lop","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"American Sable","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Angora Rabbit","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Belgian Hare","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Beveren","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Britannia Petite","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Bunny Rabbit","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Californian","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Champagne D'Argent","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Checkered Giant","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Chinchilla","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Cinnamon","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Creme D'Argent","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Dutch","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Dwarf","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Dwarf Eared","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"English Lop","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"English Spot","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Flemish Giant","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Florida White","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"French Lop","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Harlequin","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Havana","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Himalayan","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Holland Lop","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Hotot","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Jersey Wooly","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Lilac","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Lionhead","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Lop Eared","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Mini Lop","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Mini Rex","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Netherland Dwarf","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"New Zealand","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Palomino","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Polish","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Rex","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Rhinelander","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Satin","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Silver","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Silver Fox","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Silver Marten","_links":{"type":{"href":"/v2/types/rabbit"}}},
        {"name":"Tan","_links":{"type":{"href":"/v2/types/rabbit"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/rabbit"
        },
        "breeds":{
            "href":"/v2/types/rabbit/breeds"
        }
    }
    },
    SMALL_FURRY : {
    "name":"Small & Furry",
    "coats":[
        "Hairless",
        "Short",
        "Long"
    ],
    "colors":[
        "Agouti",
        "Albino",
        "Black",
        "Black Sable",
        "Blue / Gray",
        "Brown / Chocolate",
        "Calico",
        "Champagne",
        "Cinnamon",
        "Cream",
        "Orange / Red",
        "Sable",
        "Tan",
        "Tortoiseshell",
        "White",
        "White (Dark-Eyed)"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"Abyssinian","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Chinchilla","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Degu","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Dwarf Hamster","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Ferret","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Gerbil","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Guinea Pig","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Hamster","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Hedgehog","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Mouse","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Peruvian","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Prairie Dog","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Rat","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Rex","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Short-Haired","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Silkie / Sheltie","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Skunk","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Sugar Glider","_links":{"type":{"href":"/v2/types/small-furry"}}},
        {"name":"Teddy","_links":{"type":{"href":"/v2/types/small-furry"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/small-furry"
        },
        "breeds":{
            "href":"/v2/types/small-furry/breeds"
        }
    }
    },
    HORSE : {
    "name":"Horse",
    "coats":[

    ],
    "colors":[
        "Appaloosa",
        "Bay",
        "Bay Roan",
        "Black",
        "Blue Roan",
        "Brown",
        "Buckskin",
        "Champagne",
        "Chestnut / Sorrel",
        "Cremello",
        "Dapple Gray",
        "Dun",
        "Gray",
        "Grullo",
        "Liver",
        "Paint",
        "Palomino",
        "Perlino",
        "Piebald",
        "Pinto",
        "Red Roan",
        "Silver Bay",
        "Silver Buckskin",
        "Silver Dapple",
        "White"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"Appaloosa","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Arabian","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Belgian","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Clydesdale","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Connemara","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Curly Horse","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Donkey","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Draft","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Friesian","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Gaited","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Grade","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Haflinger","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Icelandic Horse","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Lipizzan","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Miniature Horse","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Missouri Foxtrotter","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Morgan","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Mule","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Mustang","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Paint / Pinto","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Palomino","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Paso Fino","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Percheron","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Peruvian Paso","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Pony","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Pony of the Americas","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Quarterhorse","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Rocky Mountain Horse","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Saddlebred","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Shetland Pony","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Standardbred","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Tennessee Walker","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Thoroughbred","_links":{"type":{"href":"/v2/types/horse"}}},
        {"name":"Warmblood","_links":{"type":{"href":"/v2/types/horse"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/horse"
        },
        "breeds":{
            "href":"/v2/types/horse/breeds"
        }
    }
    },
    BIRD : {
    "name":"Bird",
    "coats":[
    ],
    "colors":[
        "Black",
        "Blue",
        "Brown",
        "Buff",
        "Gray",
        "Green",
        "Olive",
        "Orange",
        "Pink",
        "Purple / Violet",
        "Red",
        "Rust / Rufous",
        "Tan",
        "White",
        "Yellow"
    ],
    "genders":[
        "Male",
        "Female",
        "Unknown"
    ],
    "breeds":[
        {"name":"African Grey","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Amazon","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Brotogeris","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Budgie / Budgerigar","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Button-Quail","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Caique","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Canary","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Chicken","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Cockatiel","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Cockatoo","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Conure","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Dove","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Duck","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Eclectus","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Emu","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Finch","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Goose","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Guinea Fowl","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Kakariki","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Lory / Lorikeet","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Lovebird","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Macaw","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Ostrich","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Parakeet (Other)","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Parrot (Other)","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Parrotlet","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Peacock / Peafowl","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Pheasant","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Pigeon","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Pionus","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Poicephalus / Senegal","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Quail","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Quaker Parakeet","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Rhea","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Ringneck / Psittacula","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Rosella","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Swan","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Toucan","_links":{"type":{"href":"/v2/types/bird"}}},
        {"name":"Turkey","_links":{"type":{"href":"/v2/types/bird"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/bird"
        },
        "breeds":{
            "href":"/v2/types/bird/breeds"
        }
    }
    },
    SCALES_FINS_OTHER : {
    "name":"Scales, Fins & Other",
    "coats":[

    ],
    "colors":[
        "Black",
        "Blue",
        "Brown",
        "Gray",
        "Green",
        "Iridescent",
        "Orange",
        "Purple",
        "Red",
        "Tan",
        "White",
        "Yellow"
    ],
    "genders":[
        "Male",
        "Female",
        "Unknown"
    ],
    "breeds":[
        {"name":"Asian Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Ball Python","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Bearded Dragon","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Boa","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Boa Constrictor","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Bull","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Bullfrog","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Burmese Python","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Chameleon","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Corn / Rat","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Eastern Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Fire Salamander","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Fire-Bellied","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Fire-Bellied Newt","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Florida Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Freshwater Fish","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Frog","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Garter / Ribbon","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Gecko","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Goldfish","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Hermit Crab","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Horned Frog","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Iguana","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"King / Milk","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Leopard","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Leopard Frog","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Lizard","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Mississippi Map Turtle","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Monitor","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Mud","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Musk","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Oregon Newt","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Ornamental Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Other","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Paddle Tailed Newt","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Painted","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Python","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Red Foot","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Red-Eared Slider","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Russian","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Saltwater Fish","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Scorpion","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Snake","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Snapping","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Soft Shell","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Southern","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Sulcata","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Tarantula","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Three-Toed Box","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Tiger Salamander","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Toad","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Tortoise","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Tree Frog","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Turtle","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Uromastyx","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Water Dragon","_links":{"type":{"href":"/v2/types/scales-fins-other"}}},
        {"name":"Yellow-Bellied Slider","_links":{"type":{"href":"/v2/types/scales-fins-other"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/scales-fins-other"
        },
        "breeds":{
            "href":"/v2/types/scales-fins-other/breeds"
        }
    }
    },
    BARNYARD : {
    "name":"Barnyard",
    "coats":[
        "Short",
        "Long"
    ],
    "colors":[
        "Agouti",
        "Black",
        "Black & White",
        "Brindle",
        "Brown",
        "Gray",
        "Pink",
        "Red",
        "Roan",
        "Spotted",
        "Tan",
        "White"
    ],
    "genders":[
        "Male",
        "Female"
    ],
    "breeds":[
        {"name":"Alpaca","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Alpine","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Angora","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Angus","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Barbados","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Boer","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Cow","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Duroc","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Goat","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Hampshire","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Holstein","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Jersey","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"LaMancha","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Landrace","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Llama","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Merino","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Mouflon","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Myotonic / Fainting","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Nigerian Dwarf","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Nubian","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Oberhasli","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Pig","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Pot Bellied","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Pygmy","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Saanen","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Sheep","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Shetland","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Toggenburg","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Vietnamese Pot Bellied","_links":{"type":{"href":"/v2/types/barnyard"}}},
        {"name":"Yorkshire","_links":{"type":{"href":"/v2/types/barnyard"}}}
    ],
    "_links":{
        "self":{
            "href":"/v2/types/barnyard"
        },
        "breeds":{
            "href":"/v2/types/barnyard/breeds"
        }
    }
}

});