export const fixed_listings = [
    {
        "email":"catnaps@fureverfriends.com",
        "account_type":"Private Owner",
        "phone_number":"1234567890",
        "username":"CatNaps",
        "first_name":"David",
        "user_zip":"17112",
        "favorites":[

        ],
        "pet_listings":[
            {"id": "50936491", "type": "dog"},
            {"id": "50936489", "type": "dog"},
            {"id": "50936481", "type": "dog"},
            {"id": "50936295", "type": "dog"},
            {"id": "50936244", "type": "dog"},
            {"id": "50936217", "type": "cat"},
            {"id": "50936178", "type": "cat"},
            {"id": "50935753", "type": "cat"},
            {"id": "50935755", "type": "cat"},
            {"id": "50935744", "type": "cat"},
            {"id": "50935580", "type": "cat"},
            {"id": "50936308", "type": "dog"}
        ],
        "last_name":"Door",
        "latitude":"",
        "user_bio":"",
        "longitude":""
    },
    {
        "username":"DogBiscuits",
        "email":"dogbiscuits@fureverfriends.com",
        "latitude":"",
        "first_name":"Brandon",
        "user_zip":"17112",
        "pet_listings":[
            {
                "id":"50928566",
                "type":"small_furry"
            },
            {
                "id":"50934392",
                "type":"small_furry"
            },
            {
                "id":"50936314",
                "type":"dog"
            },
            {
                "id":"50936180",
                "type":"cat"
            },
            {
                "id":"50936187",
                "type":"cat"
            },
            {
                "id":"50935703",
                "type":"cat"
            },
            {
                "id":"50935746",
                "type":"cat"
            },
            {
                "id":"50935709",
                "type":"cat"
            },
            {
                "id":"50935434",
                "type":"cat"
            },
            {
                "id":"50936312",
                "type":"dog"
            }
        ],
        "phone_number":"7174561234",
        "longitude":"",
        "account_type":"Adopter",
        "last_name":"Boon",
        "user_bio":"",
        "favorites":[

        ]
    },
    {
        "phone_number":"7171234567",
        "username":"Dogs4Ever",
        "latitude":"",
        "user_bio":"",
        "first_name":"Jane",
        "email":"dogs4ever@fureverfriends.com",
        "user_zip":"11712",
        "pet_listings":[
            {
                "id":"50934798",
                "type":"scales_fins_other"
            },
            {
                "id":"50936279",
                "type":"small_furry"
            },
            {
                "id":"50935809",
                "type":"small_furry"
            },
            {
                "id":"50934799",
                "type":"scales_fins_other"
            },
            {
                "id":"50930583",
                "type":"small_furry"
            },
            {
                "id":"50936296",
                "type":"dog"
            },
            {
                "id":"50935539",
                "type":"cat"
            },
            {
                "id":"50935554",
                "type":"cat"
            }
        ],
        "account_type":"Private Owner",
        "favorites":[

        ],
        "longitude":"",
        "last_name":"Good"
    },
    {
        "longitude":"",
        "account_type":"Private Owner",
        "favorites":[

        ],
        "pet_listings":[
            {
                "id":"50882068",
                "type":"small_furry"
            },
            {
                "id":"50932983",
                "type":"rabbit"
            },
            {
                "id":"50934435",
                "type":"small_furry"
            },
            {
                "id":"50932395",
                "type":"rabbit"
            },
            {
                "id":"50936484",
                "type":"dog"
            },
            {
                "id":"50936497",
                "type":"cat"
            },
            {
                "id":"50935732",
                "type":"dog"
            },
            {
                "id":"50936519",
                "type":"cat"
            },
            {
                "id":"50936210",
                "type":"cat"
            },
            {
                "id":"50935780",
                "type":"cat"
            }
        ],
        "latitude":"",
        "first_name":"Disha",
        "username":"dpatel",
        "email":"dvp5392@gmail.com",
        "last_name":"Patel",
        "phone_number":"2158916966",
        "user_bio":"",
        "user_zip":"17057"
    },
    {
        "latitude":"",
        "user_zip":"17057",
        "username":"avocoder123",
        "pet_listings":[
            {
                "id":"50931636",
                "type":"rabbit"
            },
            {
                "id":"50934846",
                "type":"small_furry"
            },
            {
                "id":"50882420",
                "type":"small_furry"
            },
            {
                "id":"50932961",
                "type":"bird"
            },
            {
                "id":"50932023",
                "type":"rabbit"
            },
            {
                "id":"50936496",
                "type":"dog"
            },
            {
                "id":"50935651",
                "type":"cat"
            }
        ],
        "longitude":"",
        "email":"dvp5392@psu.edu",
        "user_bio":"",
        "first_name":"Disha",
        "last_name":"Patel",
        "phone_number":"2158916966",
        "favorites":[

        ],
        "account_type":"Adopter",
        "textarea1":"Dogs"
    },
    {
        "phone_number":"1234567890",
        "account_type":"Organization",
        "last_name":"Doe",
        "longitude":"",
        "pet_listings":[
            {
                "id":"50930679",
                "type":"rabbit"
            },
            {
                "id":"50931523",
                "type":"rabbit"
            },
            {
                "id":"50934346",
                "type":"small_furry"
            },
            {
                "id":"50934716",
                "type":"small_furry"
            },
            {
                "id":"50936498",
                "type":"dog"
            },
            {
                "id":"50936261",
                "type":"dog"
            },
            {
                "id":"50936301",
                "type":"cat"
            },
            {
                "id":"50936205",
                "type":"cat"
            },
            {
                "id":"50935747",
                "type":"cat"
            }
        ],
        "user_zip":"17112",
        "latitude":"",
        "favorites":[

        ],
        "username":"FuzzyPetRescue",
        "email":"fuzzypetrescue@fureverfriends.com",
        "first_name":"Sandy",
        "user_bio":""
    },
    {
        "longitude":"",
        "account_type":"Adopter",
        "user_zip":"17522",
        "favorites":[

        ],
        "user_bio":"I like dogs and cats.",
        "phone_number":"7177992809",
        "email":"jpa5180@psu.edu",
        "latitude":"",
        "first_name":"Jean",
        "pet_listings":[
            {
                "id":"50928775",
                "type":"small_furry"
            },
            {
                "id":"50932770",
                "type":"rabbit"
            },
            {
                "id":"50929466",
                "type":"small_furry"
            },
            {
                "id":"50934361",
                "type":"small_furry"
            },
            {
                "id":"50936268",
                "type":"dog"
            },
            {
                "id":"50936302",
                "type":"cat"
            },
            {
                "id":"50936211",
                "type":"dog"
            },
            {
                "id":"50936546",
                "type":"cat"
            },
            {
                "id":"50936039",
                "type":"cat"
            },
            {
                "id":"50936471",
                "type":"dog"
            }
        ],
        "last_name":"Astudillo",
        "username":"jpa5180"
    },
    {
        "user_bio":"I like turtles!",
        "email":"jpastudillo123@gmail.com",
        "username":"jpa123",
        "user_zip":"17522",
        "phone_number":"7177992809",
        "account_type":"Private Owner",
        "first_name":"JP",
        "favorites":[

        ],
        "last_name":"Guerra",
        "latitude":"",
        "pet_listings":[
            {
                "id":"50928834",
                "type":"small_furry"
            },
            {
                "id":"50932382",
                "type":"rabbit"
            },
            {
                "id":"50936505",
                "type":"dog"
            },
            {
                "id":"50935392",
                "type":"small_furry"
            },
            {
                "id":"50929543",
                "type":"small_furry"
            },
            {
                "id":"50936488",
                "type":"dog"
            },
            {
                "id":"50936297",
                "type":"dog"
            },
            {
                "id":"50936181",
                "type":"dog"
            },
            {
                "id":"50936241",
                "type":"cat"
            },
            {
                "id":"50936515",
                "type":"cat"
            },
            {
                "id":"50935790",
                "type":"cat"
            },
            {
                "id":"50935535",
                "type":"cat"
            }
        ],
        "longitude":""
    },
    {
        "favorites":[

        ],
        "last_name":"Redding",
        "first_name":"Kathy",
        "user_zip":"17112",
        "account_type":"Adopter",
        "pet_listings":[
            {
                "id":"50932981",
                "type":"small_furry"
            },
            {
                "id":"50928560",
                "type":"small_furry"
            },
            {
                "id":"50883585",
                "type":"small_furry"
            },
            {
                "id":"50931522",
                "type":"bird"
            },
            {
                "id":"50929725",
                "type":"small_furry"
            },
            {
                "id":"50934845",
                "type":"small_furry"
            },
            {
                "id":"50930158",
                "type":"small_furry"
            },
            {
                "id":"50936486",
                "type":"dog"
            },
            {
                "id":"50936269",
                "type":"dog"
            },
            {
                "id":"50935589",
                "type":"dog"
            },
            {
                "id":"50936168",
                "type":"cat"
            },
            {
                "id":"50936075",
                "type":"cat"
            },
            {
                "id":"50935992",
                "type":"cat"
            }
        ],
        "latitude":"",
        "user_bio":"",
        "phone_number":"5671234567",
        "username":"KittenPaws",
        "email":"kittenpaws@fureverfriends.com",
        "longitude":""
    },
    {
        "latitude":"",
        "pet_listings":[
            {
                "id":"50932882",
                "type":"bird"
            },
            {
                "id":"50936514",
                "type":"dog"
            },
            {
                "id":"50936521",
                "type":"dog"
            },
            {
                "id":"50935811",
                "type":"small_furry"
            },
            {
                "id":"50936219",
                "type":"dog"
            },
            {
                "id":"50936263",
                "type":"cat"
            },
            {
                "id":"50935775",
                "type":"cat"
            },
            {
                "id":"50936310",
                "type":"dog"
            }
        ],
        "user_bio":"",
        "longitude":"",
        "last_name":"Frasier",
        "user_zip":"17112",
        "account_type":"Adopter",
        "favorites":[

        ],
        "username":"LazySundayFurball",
        "email":"lazysundayfurball@fureverfriends.com",
        "first_name":"Sara",
        "phone_number":"4569087654"
    },
    {
        "last_name":"Mitchell",
        "user_bio":"",
        "pet_listings":[
            {
                "id":"50932246",
                "type":"small_furry"
            },
            {
                "id":"50936513",
                "type":"dog"
            },
            {
                "id":"50935167",
                "type":"rabbit"
            },
            {
                "id":"50936494",
                "type":"dog"
            },
            {
                "id":"50936273",
                "type":"dog"
            },
            {
                "id":"50936280",
                "type":"dog"
            },
            {
                "id":"50936292",
                "type":"cat"
            },
            {
                "id":"50935800",
                "type":"cat"
            },
            {
                "id":"50935983",
                "type":"cat"
            },
            {
                "id":"50935752",
                "type":"cat"
            },
            {
                "id":"50935652",
                "type":"cat"
            },
            {
                "id":"50935641",
                "type":"cat"
            },
            {
                "id":"50935546",
                "type":"cat"
            }
        ],
        "favorites":[

        ],
        "phone_number":"7179104037",
        "email":"micercutetoo@fureverfriends.com",
        "username":"MiceRCuteToo",
        "latitude":"",
        "first_name":"Mandy",
        "user_zip":"17112",
        "longitude":"",
        "account_type":"Private Owner"
    },
    {
        "last_name":"Smith",
        "favorites":[

        ],
        "first_name":"John",
        "email":"petlover123@fureverfriends.com",
        "username":"PetLover123",
        "user_zip":"17112",
        "phone_number":"1234567890",
        "latitude":"",
        "longitude":"",
        "user_bio":"",
        "account_type":"Private Owner",
        "pet_listings":[
            {
                "id":"50932910",
                "type":"small_furry"
            },
            {
                "id":"50934255",
                "type":"small_furry"
            },
            {
                "id":"50936507",
                "type":"dog"
            },
            {
                "id":"50936305",
                "type":"dog"
            },
            {
                "id":"50936274",
                "type":"dog"
            },
            {
                "id":"50935749",
                "type":"cat"
            },
            {
                "id":"50935980",
                "type":"cat"
            }
        ]
    },
    {
        "email":"rabbitears34@fureverfriends.com",
        "favorites":[

        ],
        "phone_number":"2341236543",
        "username":"RabbitEars34",
        "pet_listings":[
            {
                "id":"50934465",
                "type":"small_furry"
            },
            {
                "id":"50934483",
                "type":"small_furry"
            },
            {
                "id":"50932985",
                "type":"rabbit"
            },
            {
                "id":"50932695",
                "type":"rabbit"
            },
            {
                "id":"50934513",
                "type":"small_furry"
            },
            {
                "id":"50936468",
                "type":"dog"
            }
        ],
        "account_type":"Adopter",
        "last_name":"Wilson",
        "first_name":"Frank",
        "user_bio":"",
        "longitude":"",
        "latitude":"",
        "user_zip":"17057"
    },
    {
        "email":"riseandmeow@fureverfriends.com",
        "phone_number":"4561234567",
        "longitude":"",
        "latitude":"",
        "favorites":[

        ],
        "last_name":"Rivers",
        "user_bio":"",
        "first_name":"Chris",
        "pet_listings":[
            {
                "id":"50930993",
                "type":"rabbit"
            },
            {
                "id":"50936501",
                "type":"dog"
            },
            {
                "id":"50936502",
                "type":"dog"
            },
            {
                "id":"50930177",
                "type":"bird"
            },
            {
                "id":"50933639",
                "type":"small_furry"
            },
            {
                "id":"50936248",
                "type":"cat"
            },
            {
                "id":"50936552",
                "type":"cat"
            },
            {
                "id":"50936265",
                "type":"cat"
            },
            {
                "id":"50935750",
                "type":"cat"
            }
        ],
        "user_zip":"17057",
        "username":"RiseAndMeow",
        "account_type":"Private Owner"
    },
    {
        "pet_listings":[
            {
                "id":"50928526",
                "type":"bird"
            },
            {
                "id":"50936535",
                "type":"dog"
            },
            {
                "id":"50928751",
                "type":"small_furry"
            },
            {
                "id":"50935350",
                "type":"rabbit"
            },
            {
                "id":"50936246",
                "type":"dog"
            },
            {
                "id":"50936198",
                "type":"dog"
            },
            {
                "id":"50936131",
                "type":"cat"
            },
            {
                "id":"50936051",
                "type":"cat"
            },
            {
                "id":"50935409",
                "type":"cat"
            },
            {
                "id":"50935748",
                "type":"cat"
            }
        ],
        "last_name":"Kettell",
        "favorites":[

        ],
        "username":"Skettles",
        "email":"sakettell@gmail.com",
        "account_type":"Private Owner",
        "first_name":"Sarah",
        "user_zip":"17112",
        "user_bio":"",
        "latitude":"",
        "longitude":"",
        "phone_number":"5209558488"
    },
    {
        "last_name":"Sahay",
        "email":"surabhi.sahay24@gmail.com",
        "favorites":[

        ],
        "latitude":"",
        "account_type":"Private Owner",
        "user_zip":"17057",
        "username":"suri24",
        "first_name":"Surabhi",
        "longitude":"",
        "phone_number":"5183605068",
        "user_bio":"",
        "pet_listings":[
            {
                "id":"50935812",
                "type":"small_furry"
            },
            {
                "id":"50936493",
                "type":"dog"
            },
            {
                "id":"50936510",
                "type":"dog"
            },
            {
                "id":"50936516",
                "type":"dog"
            },
            {
                "id":"50929383",
                "type":"bird"
            },
            {
                "id":"50936473",
                "type":"dog"
            },
            {
                "id":"50936299",
                "type":"dog"
            },
            {
                "id":"50935776",
                "type":"cat"
            },
            {
                "id":"50935650",
                "type":"cat"
            },
            {
                "id":"50935594",
                "type":"cat"
            }
        ]
    },
    {
        "user_zip":"17112",
        "username":"SarahKettell",
        "phone_number":"5209558488",
        "user_bio":"",
        "latitude":"",
        "pet_listings":[
            {
                "id":"50933643",
                "type":"small_furry"
            },
            {
                "id":"50936293",
                "type":"dog"
            },
            {
                "id":"50936262",
                "type":"cat"
            },
            {
                "id":"50936135",
                "type":"cat"
            },
            {
                "id":"50935710",
                "type":"cat"
            },
            {
                "id":"50935612",
                "type":"cat"
            }
        ],
        "last_name":"Kettell",
        "account_type":"Adopter",
        "email":"sxk1552@psu.edu",
        "longitude":"",
        "favorites":[

        ],
        "first_name":"Sarah"
    }
]
